"""Migration pipeline tests.

Milestone 0 ships no tables, so the round-trip and drift assertions below pass
trivially today. They are written now, not later, because the class of bug they
catch - a model changed without a migration, or a downgrade that loses data -
is introduced the moment Milestone 1 adds the first table. A drift test written
after the drift has already happened is much harder to make pass.

``alembic check`` is the single most valuable test in this file long-term: it
compares ORM metadata against the migrated schema and fails on any difference.
It is the reason the constraint naming convention exists in
``memhub.persistence.base``.
"""

from __future__ import annotations

import asyncio

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from memhub.config import Settings
from tests.conftest import _alembic_config

pytestmark = pytest.mark.integration


@pytest.fixture
def db_url(settings: Settings, test_database: str) -> str:
    return settings.sqlalchemy_url.set(database=test_database).render_as_string(hide_password=False)


async def test_migrations_reach_head(engine: AsyncEngine) -> None:
    """The module database is cloned from the migrated template, so it must
    already be stamped at head."""
    async with engine.connect() as conn:
        stamped = (await conn.execute(text("SELECT version_num FROM alembic_version"))).scalar_one()

    script = ScriptDirectory.from_config(_alembic_config("unused"))
    assert stamped == script.get_current_head()


async def test_single_head_revision() -> None:
    """More than one head means a branching migration history, which produces
    non-deterministic upgrade order. Fail loudly the moment it happens."""
    script = ScriptDirectory.from_config(_alembic_config("unused"))
    heads = script.get_heads()
    assert len(heads) == 1, f"Expected exactly one migration head, found {heads}"


async def test_upgrade_downgrade_upgrade_round_trip(db_url: str, engine: AsyncEngine) -> None:
    """Every migration must be reversible.

    An irreversible migration is a deployment that cannot be rolled back. If a
    future migration genuinely cannot be reversed, that must be a conscious,
    documented decision rather than something discovered during an incident.
    """
    cfg = _alembic_config(db_url)

    await asyncio.to_thread(command.downgrade, cfg, "base")
    async with engine.connect() as conn:
        exists = (
            await conn.execute(text("SELECT to_regclass('public.alembic_version')"))
        ).scalar_one()
    # The version table survives a downgrade to base; it is simply emptied.
    assert exists is not None

    await asyncio.to_thread(command.upgrade, cfg, "head")

    script = ScriptDirectory.from_config(cfg)
    async with engine.connect() as conn:
        stamped = (await conn.execute(text("SELECT version_num FROM alembic_version"))).scalar_one()
    assert stamped == script.get_current_head()


async def test_no_drift_between_models_and_migrations(db_url: str) -> None:
    """``alembic check``: ORM metadata must match the migrated schema exactly.

    This is the test that catches 'someone edited a model and forgot the
    migration'. It only works because ``memhub.persistence.base`` pins a
    constraint naming convention - without it, autogenerate reports phantom
    differences on every unnamed constraint.
    """
    cfg = _alembic_config(db_url)
    try:
        await asyncio.to_thread(command.check, cfg)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "Schema drift detected between ORM models and migrations.\n"
            f"{exc}\n"
            "Run: alembic revision --autogenerate -m '<description>'"
        )
