"""projects and memories

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-30 21:01:19.811615

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9._-]{0,62}[a-z0-9]$'", name=op.f("ck_projects_slug_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("slug", name=op.f("uq_projects_slug")),
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'ACTIVE'"), nullable=False),
        sa.Column("current_revision_no", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("importance", sa.SmallInteger(), server_default=sa.text("50"), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column("superseded_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'DELETED') = (deleted_at IS NOT NULL)",
            name=op.f("ck_memories_deleted_consistent"),
        ),
        sa.CheckConstraint(
            "(status = 'SUPERSEDED') = (superseded_at IS NOT NULL)",
            name=op.f("ck_memories_superseded_consistent"),
        ),
        sa.CheckConstraint(
            "status <> 'SUPERSEDED' OR superseded_by_id IS NOT NULL",
            name=op.f("ck_memories_superseded_has_target"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUPERSEDED','DELETED')", name=op.f("ck_memories_status_known")
        ),
        sa.CheckConstraint(
            "type <> 'TASK' OR expires_at IS NOT NULL", name=op.f("ck_memories_task_needs_ttl")
        ),
        sa.CheckConstraint(
            "type IN ('DECISION','CONSTRAINT','FACT','TASK')", name=op.f("ck_memories_type_known")
        ),
        sa.CheckConstraint("current_revision_no >= 1", name=op.f("ck_memories_revision_positive")),
        sa.CheckConstraint(
            "importance BETWEEN 0 AND 100", name=op.f("ck_memories_importance_range")
        ),
        sa.CheckConstraint(
            "superseded_by_id IS DISTINCT FROM id", name=op.f("ck_memories_no_self_supersede")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_memories_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id", "project_id"],
            ["memories.id", "memories.project_id"],
            name=op.f("fk_memories_superseded_by_id_project_id_memories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_memories_id_project_id")),
    )
    op.create_index(
        "ix_memories_expires_at",
        "memories",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL AND status = 'ACTIVE'"),
    )
    op.create_index(
        "ix_memories_project_id_type_importance",
        "memories",
        ["project_id", "type", sa.literal_column("importance DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_index(
        "ix_memories_superseded_by_id",
        "memories",
        ["superseded_by_id"],
        unique=False,
        postgresql_where=sa.text("superseded_by_id IS NOT NULL"),
    )
    op.create_table(
        "project_aliases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("value_norm", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('git_remote','workspace_path')", name=op.f("ck_project_aliases_kind_known")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_aliases_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_aliases")),
        sa.UniqueConstraint("kind", "value_norm", name=op.f("uq_project_aliases_kind_value_norm")),
    )
    op.create_index(
        "ix_project_aliases_project_id", "project_aliases", ["project_id"], unique=False
    )
    op.create_table(
        "memory_revisions",
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("hash_version", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("author_client", sa.Text(), nullable=False),
        sa.Column("author_kind", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "author_kind IN ('agent','human_confirmed','import')",
            name=op.f("ck_memory_revisions_author_kind_known"),
        ),
        sa.CheckConstraint(
            "cardinality(tags) <= 16", name=op.f("ck_memory_revisions_tags_bounded")
        ),
        sa.CheckConstraint(
            "length(content) BETWEEN 1 AND 8192", name=op.f("ck_memory_revisions_content_length")
        ),
        sa.CheckConstraint("revision_no >= 1", name=op.f("ck_memory_revisions_revision_positive")),
        sa.ForeignKeyConstraint(
            ["memory_id", "project_id"],
            ["memories.id", "memories.project_id"],
            name=op.f("fk_memory_revisions_memory_id_project_id_memories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("memory_id", "revision_no", name=op.f("pk_memory_revisions")),
    )
    op.create_index(
        "ix_memory_revisions_project_id", "memory_revisions", ["project_id"], unique=False
    )
    op.create_index(
        "uq_memory_revisions_memory_id",
        "memory_revisions",
        ["memory_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_memory_revisions_memory_id",
        table_name="memory_revisions",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index("ix_memory_revisions_project_id", table_name="memory_revisions")
    op.drop_table("memory_revisions")
    op.drop_index("ix_project_aliases_project_id", table_name="project_aliases")
    op.drop_table("project_aliases")
    op.drop_index(
        "ix_memories_superseded_by_id",
        table_name="memories",
        postgresql_where=sa.text("superseded_by_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_memories_project_id_type_importance",
        table_name="memories",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(
        "ix_memories_expires_at",
        table_name="memories",
        postgresql_where=sa.text("expires_at IS NOT NULL AND status = 'ACTIVE'"),
    )
    op.drop_table("memories")
    op.drop_table("projects")
    # ### end Alembic commands ###
