"""idempotency keys and audit events

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-30 21:41:50.412425

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("memory_id", sa.UUID(), nullable=True),
        sa.Column("revision_no", sa.Integer(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("actor_client", sa.Text(), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('remember','revise','forget','supersede','purge')",
            name=op.f("ck_audit_events_action_known"),
        ),
        sa.CheckConstraint(
            "outcome IN ('ok','conflict','dedup','replay','rejected')",
            name=op.f("ck_audit_events_outcome_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_memory_id_at",
        "audit_events",
        ["memory_id", sa.literal_column("at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_project_id_at",
        "audit_events",
        ["project_id", sa.literal_column("at DESC")],
        unique=False,
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("client_request_id", sa.Text(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("request_fingerprint", sa.LargeBinary(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now() + interval '7 days'"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state <> 'COMPLETED' OR response IS NOT NULL",
            name=op.f("ck_idempotency_keys_completed_has_response"),
        ),
        sa.CheckConstraint(
            "state IN ('IN_PROGRESS','COMPLETED')", name=op.f("ck_idempotency_keys_state_known")
        ),
        sa.CheckConstraint(
            "length(client_request_id) BETWEEN 8 AND 128",
            name=op.f("ck_idempotency_keys_request_id_length"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_idempotency_keys_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "client_request_id", name=op.f("pk_idempotency_keys")
        ),
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_audit_events_project_id_at", table_name="audit_events")
    op.drop_index("ix_audit_events_memory_id_at", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
