"""dedup keys and attestations

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-30 21:58:00.354835

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_attestations",
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.Text(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "first_seen_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("times_seen", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "times_seen >= 1", name=op.f("ck_memory_attestations_times_seen_positive")
        ),
        sa.ForeignKeyConstraint(
            ["memory_id", "project_id"],
            ["memories.id", "memories.project_id"],
            name=op.f("fk_memory_attestations_memory_id_project_id_memories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("memory_id", "client_name", name=op.f("pk_memory_attestations")),
    )
    op.create_table(
        "memory_dedup_keys",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("hash_version", sa.SmallInteger(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["memory_id", "project_id"],
            ["memories.id", "memories.project_id"],
            name=op.f("fk_memory_dedup_keys_memory_id_project_id_memories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "hash_version", "content_hash", name=op.f("pk_memory_dedup_keys")
        ),
    )
    op.create_index(
        "ix_memory_dedup_keys_memory_id", "memory_dedup_keys", ["memory_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memory_dedup_keys_memory_id", table_name="memory_dedup_keys")
    op.drop_table("memory_dedup_keys")
    op.drop_table("memory_attestations")
    # ### end Alembic commands ###
