"""full text search

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-31 12:49:33.535282

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "memory_revisions",
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_memory_revisions_content_tsv",
        "memory_revisions",
        ["content_tsv"],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("is_current"),
    )
    op.create_index(
        "ix_memory_revisions_tags",
        "memory_revisions",
        ["tags"],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("is_current"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_memory_revisions_tags",
        table_name="memory_revisions",
        postgresql_using="gin",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index(
        "ix_memory_revisions_content_tsv",
        table_name="memory_revisions",
        postgresql_using="gin",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_column("memory_revisions", "content_tsv")
    # ### end Alembic commands ###
