"""vector storage and embedding outbox

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-31 13:42:10.927924

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Must precede any table using the vector type. The pgvector/pgvector
    # image ships the extension; this is what actually enables it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "next_attempt_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('PENDING','DONE','DEAD')", name=op.f("ck_embedding_jobs_state_known")
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_embedding_jobs_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["memory_id", "revision_no"],
            ["memory_revisions.memory_id", "memory_revisions.revision_no"],
            name=op.f("fk_embedding_jobs_memory_id_revision_no_memory_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_jobs")),
        sa.UniqueConstraint(
            "memory_id",
            "revision_no",
            "model",
            name=op.f("uq_embedding_jobs_memory_id_revision_no_model"),
        ),
    )
    op.create_index(
        "ix_embedding_jobs_next_attempt_at",
        "embedding_jobs",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("state = 'PENDING'"),
    )
    op.create_table(
        "memory_embeddings",
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("dim", sa.SmallInteger(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("dim = 384", name=op.f("ck_memory_embeddings_dim_matches_column")),
        sa.ForeignKeyConstraint(
            ["memory_id", "revision_no"],
            ["memory_revisions.memory_id", "memory_revisions.revision_no"],
            name=op.f("fk_memory_embeddings_memory_id_revision_no_memory_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "memory_id", "revision_no", "model", name=op.f("pk_memory_embeddings")
        ),
    )
    op.create_index(
        "ix_memory_embeddings_hnsw",
        "memory_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_memory_embeddings_project_id", "memory_embeddings", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # The extension is deliberately NOT dropped. Another database in the same
    # cluster may be using it, and dropping it would cascade into their
    # columns - a downgrade of this schema has no business doing that.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memory_embeddings_project_id", table_name="memory_embeddings")
    op.drop_index(
        "ix_memory_embeddings_hnsw",
        table_name="memory_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("memory_embeddings")
    op.drop_index(
        "ix_embedding_jobs_next_attempt_at",
        table_name="embedding_jobs",
        postgresql_where=sa.text("state = 'PENDING'"),
    )
    op.drop_table("embedding_jobs")
    # ### end Alembic commands ###
